### ISSUE TITLE
imagemin response code is 404 (Not Found)

### ISSUE THREAD

**Issue by albatrosary** [albatrosary/generator-angular-eggs#2]
Error in the `npm install`:

```
> optipng-bin@3.0.1 postinstall /Users/albatrosary/Books/temple/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ⚠ https://raw.githubusercontent.com/imagemin/optipng-bin/v3.0.1/vendor/osx/optipng response code is 404 (Not Found)
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/Users/albatrosary/Books/temple/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/Users/albatrosary/Books/temple/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install
Command failed: /bin/sh -c make install
pngrtran.c:97:1: warning: unused function 'png_rtran_ok' [-Wunused-function]
png_rtran_ok(png_structrp png_ptr, int need_IHDR)
^
1 warning generated.
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpng.a(pngpread.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpng.a(pngwtran.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpng.a(pngpread.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpng.a(pngwtran.o) has no symbols
pngxmem.c:37:32: warning: comparison of constant 2305843009213693951 with expression of type 'png_uint_32' (aka 'unsigned int') is always false [-Wtautological-constant-out-of-range-compare]
   if (row_size == 0 || height > (pngx_alloc_size_t)(-1) / sizeof(png_bytep))
                        ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpngxtern.a(pngxio.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpngxtern.a(pngxio.o) has no symbols
osys.c:525:25: error: no member named 'st_atim' in 'struct stat'
        times[0] = sbuf.st_atim;
                   ~~~~ ^
osys.c:526:25: error: no member named 'st_mtim' in 'struct stat'
        times[1] = sbuf.st_mtim;
                   ~~~~ ^
osys.c:527:13: warning: implicit declaration of function 'utimensat' is invalid in C99 [-Wimplicit-function-declaration]
        if (utimensat(AT_FDCWD, dest_path, times, 0) != 0)
            ^
1 warning and 2 errors generated.
make[1]: *** [osys.o] Error 1
make: *** [install] Error 2

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
```

**Comment by albatrosary** [comment]
`grunt serve`

```
Running "concurrent:server" (concurrent) task
    Warning: Loading "sass.js" tasks...ERROR
    >> Error: dlopen(/Users/albatrosary/Books/temple/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node, 1): no suitable image found.  Did find:
    >> 	/Users/albatrosary/Books/temple/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node: truncated mach-o error: segment __LINKEDIT extends to 2288368 which is past end of file 2099164
```

**Comment by albatrosary** [comment]
What is the version of optipng-bin that is used in grunt-contrib-imagemin ?

grunt-contrib-imagemin  |  optipng-bin | 
------- | ------ | ---
0.9.0 | 3.0.1 | error
0.8.1 | 1.0.1 | ok
