### ISSUE TITLE
2 failed spec(s)

### ISSUE THREAD

**Issue by albatrosary** [albatrosary/generator-angular-eggs#40]
e2e test: protractor error

```
Running "protractor:accept" (protractor) task
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
..F

Failures:

  1) protractor sample contact - display
   Message:
     TypeError: Cannot read property '0' of null
   Stacktrace:
     TypeError: Cannot read property '0' of null
    at Array.forEach (native)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
From: Task: Asynchronous test function: beforeEach()
Error
    at [object Object].<anonymous> (/Users/albatrosary/Work/SampleApp/e2e/spec/exists.spec.js:4:3)
    at Object.<anonymous> (/Users/albatrosary/Work/SampleApp/e2e/spec/exists.spec.js:1:63)

  2) protractor sample contact - display
   Message:
     NoSuchWindowError: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=45.0.2454.99)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64)
   Stacktrace:
     NoSuchWindowError: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=45.0.2454.99)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64)
    at Array.forEach (native)
Error
    at [object Object].<anonymous> (/Users/albatrosary/Work/SampleApp/e2e/spec/exists.spec.js:48:13)
From: Task: Asynchronous test function: it()
Error
    at [object Object].<anonymous> (/Users/albatrosary/Work/SampleApp/e2e/spec/exists.spec.js:43:3)
    at Object.<anonymous> (/Users/albatrosary/Work/SampleApp/e2e/spec/exists.spec.js:1:63)

Finished in 5.277 seconds
3 tests, 7 assertions, 2 failures

[launcher] 0 instance(s) of WebDriver still running
```

**Comment by albatrosary** [comment]
To run after `grunt serve` or `grunt build`
